version: "3.8"
services:
  backend:
    image: "michaelxsteinertxcontainer/fullstack-spring-boot-2021:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev